#!/bin/bash
echo 'We are white'
for i in {1..10}
do
    ./testgame SimplePlayer cs2_drop_squad &
done
sleep 20
echo 'We are black'
for i in {1..10}
do
    ./testgame cs2_drop_squad SimplePlayer &    
done
